#! /bin/sh

sxhkd &
picom &

xsetroot -cursor_name left_ptr &
setxkbmap pl &

bspc monitor eDP -d I II III IV V VI VII VIII IX X

# Dual monitor setup:
#external_monitor=$(xrandr --query | grep 'HDMI-A-0')
#if [[ $external_monitor = *connected* ]]; then
#      xrandr --output eDP --primary --mode 2160x1440 --rotate normal --output HDMI-A-0 --mode 1680x1050 --rotate normal --right-of eDP
#fi

bspc config border_width         4
bspc config window_gap           2

bspc config normal_border_color  "#383C36"
bspc config focused_border_color "#800080"

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#feh --bg-scale $HOME/grafiki/background/wallpaper.jpg
feh --bg-scale $HOME/grafiki/background/ok.jpg
$HOME/.config/polybar/launch.sh --hack
#$HOME/.config/polybar/material/scripts/pywal.sh $HOME/grafiki/background/wallpaper.jpg

